<?php

namespace App\Support\Importer;

use Illuminate\Support\Facades\File;

class TranscriptFormatProbeWriter
{
    public function __construct(
        private readonly TranscriptFormatProbePaths $paths,
    ) {}

    /**
     * @param  array<int, array<string, mixed>>  $analyses
     */
    public function write(array $analyses): void
    {
        File::ensureDirectoryExists(dirname($this->paths->findingsPath()));

        File::put($this->paths->findingsPath(), $this->markdown($analyses));
    }

    /**
     * @param  array<int, array<string, mixed>>  $analyses
     */
    private function markdown(array $analyses): string
    {
        $profileCounts = collect($analyses)
            ->countBy(fn (array $analysis): string => (string) $analysis['candidate_profile'])
            ->sortKeys();

        $lines = [
            '# Importer Transcript Format Probe',
            '',
            'Generated by `php artisan importer:probe-formats`.',
            '',
            '## Summary',
            '',
            '- Documents analyzed: '.count($analyses),
            '- Candidate profiles: '.$profileCounts
                ->map(fn (int $count, string $profile): string => "{$profile} ({$count})")
                ->values()
                ->join(', '),
            '',
            '## Candidate Format Profiles',
            '',
        ];

        foreach ($profileCounts as $profile => $count) {
            $lines[] = "- `{$profile}`: {$count} document(s)";
        }

        $lines[] = '';
        $lines[] = '## Documents';
        $lines[] = '';

        foreach ($analyses as $analysis) {
            $lines = [
                ...$lines,
                "### `{$analysis['document_id']}`",
                '',
                "- Candidate profile: `{$analysis['candidate_profile']}`",
                "- Timestamp lines: {$analysis['timestamp_count']}",
                "- Speaker-label lines: {$analysis['speaker_label_count']}",
                "- Headings: {$analysis['heading_count']}",
                "- Bold spans: {$analysis['bold_count']}",
                '',
                '**Timestamp samples:**',
                '',
                ...$this->quoteLines($analysis['timestamp_samples']),
                '',
                '**Speaker-label samples:**',
                '',
                ...$this->quoteLines($analysis['speaker_label_samples']),
                '',
                '**Heading samples:**',
                '',
                ...$this->quoteLines($analysis['heading_samples']),
                '',
                '**Opener block:**',
                '',
                ...$this->quoteLines($analysis['opener_lines']),
                '',
                '**Closer block:**',
                '',
                ...$this->quoteLines($analysis['closer_lines']),
                '',
            ];
        }

        return implode(PHP_EOL, $lines);
    }

    /**
     * @param  array<int, string>  $lines
     * @return array<int, string>
     */
    private function quoteLines(array $lines): array
    {
        if ($lines === []) {
            return ['> none'];
        }

        return collect($lines)
            ->map(fn (string $line): string => '> '.$line)
            ->all();
    }
}
